name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "nownews"
database_id = "1a847865-ce69-452a-a87e-e42db7c13c38"
