name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "nownews"
database_id = "1a847865-ce69-452a-a87e-e42db7c13c38"

[vars]
G_CLIENT_ID = "Ov23li0RgZmjdBxH7gPM"
G_CLIENT_SECRET = "a66676a1a9d561fc8d0a2455f58231d42db27062"
JWT_SECRET = "mykey12345:“@"
INIT_TABLE = true
ENABLE_CACHE = true
